[package]
edition = "2021"
name = "egui-curve-edit"
version = "0.1.0"

[features]
default = ["serde"]
serde = ["cgmath/serde", "dep:serde"]

[dependencies]
cgmath = "0.18.0"
egui = "0.32.0"
serde = { version = "1", features = ["derive"], optional = true }
